import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ToastProvider from "./components/ToastProvider";
import { HomePageData } from "./lib/types/cms/home";
import { getSiteMetadata } from "./lib/api/home";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export async function generateMetadata(): Promise<Metadata> {
  try {
    const siteMetadata: HomePageData["data"]["site_metadata"] | undefined = await getSiteMetadata();
    return {
      title: siteMetadata?.name ?? "CVG Website",
      description: siteMetadata?.description ?? "Generated by CVG Website",
      icons: siteMetadata?.favicon?.url ? { icon: siteMetadata.favicon.url } : undefined,
    };
  } catch (e) {
    return {
      title: "CVG Website",
      description: "Generated by CVG Website",
    };
  }
}

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const siteMetadata = await getSiteMetadata().catch(() => undefined);

  return (
    <html lang="en">
      <head>
        {siteMetadata?.favicon?.url && (
          <>
            <link rel="icon" href={siteMetadata.favicon.url} />
            <link rel="shortcut icon" href={siteMetadata.favicon.url} />
          </>
        )}
      </head>
      <body className={`antialiased ${poppins.className}`}>
        {children}
        <ToastProvider />
      </body>
    </html>
  );
}
