import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "./components/layouts/NavBar";
import { Footer } from "./components/layouts/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "CVM Website",
  description: "Generated by CVM Website",
};

const Items = [
  { id: 1, content: "Home", link: "/" },
  { id: 2, content: "Our Projects", link: "/projects" },
  { id: 3, content: "Services", link: "/services" },
  { id: 4, content: "Values", link: "/values" },
  { id: 5, content: "Process", link: "/process" },
  { id: 6, content: "About Us", link: "/about" },
];
const contactItem = { id: 7, content: "Contact Us", link: "/contact" };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <NavBar items={Items} contactItem={contactItem} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
